version: '3.8'

services:
 backend:
   build:
     context: ./backend # Path to the backend Dockerfile
   ports:
     - "8080:8080"

 backend2:
   build:
     context: ./backend # Path to the backend Dockerfile
   ports:
     - "8084:8080"


 auth-backend:
   build:
     context: ./backend-auth # Path to the backend Dockerfile
   ports:
     - "5000:5000" 


 frontend:
   build:
     context: ./client # Path to the frontend Dockerfile
   ports:
     - "3000:3000"
   depends_on:
     - backend # Wait for backend service to be ready before starting frontend


 frontend2:
   build:
     context: ./client2 # Path to the frontend Dockerfile
   ports:
     - "3001:3000"
   depends_on:
     - backend # Wait for backend service to be ready before starting frontend
